In [10]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


Create a NumPy array with values [10, 20, 30, 40]

In [57]:
import numpy as np
arr1=np.array([10, 20, 30, 40])
print(arr1)

[10 20 30 40]


Print the type of the array

In [5]:
type(arr1)

numpy.ndarray

Create a 2D Array

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


Find - shape
dimension
size
datatype

In [7]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

(2, 3)
2
6
int64


Create Zero Matrix

In [10]:
arr3=np.zeros((3,2))
print(arr3)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [11]:
arr3.dtype

dtype('float64')

convert from float to int

In [15]:
arr3=arr3.astype(int)


In [14]:
print(arr3.dtype)

int64


Create a 2x4 array of ones

In [16]:
arr4= np.ones((2,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
arr4=arr4.astype(int)
print(arr4)

[[1 1 1 1]
 [1 1 1 1]]


Create a 2x2 array filled with value 7

In [21]:
arr5=np.full((2,2),7)
print(arr5)

[[7 7]
 [7 7]]


Generate 5 random numbers between 0 and 1

In [22]:
print(np.random.rand(5))               #alson in python to print rnadom no. in btween 0 to 1 we use random.rand()

[0.51779238 0.71834883 0.14522937 0.75505672 0.33963542]


Using arange Create numbers from 1 to 10

In [23]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


Create even numbers between 10 and 20

In [24]:
print(np.arange(10,21,2))

[10 12 14 16 18 20]


Create 5 evenly spaced values between 0 and 1

In [27]:
print(np.linspace(0,1,5))    #for evenly spacing we can use linspace first write from where to where you want to find then write how many you want to find

[0.   0.25 0.5  0.75 1.  ]


Indexing

In [36]:
arr1=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(arr1[0:2,0:2])

[[1 2]
 [4 5]]


In [38]:
print(arr1[0:2,1:])

[[2 3]
 [5 6]]


In [39]:
print(arr1[1:,0:2])

[[4 5]
 [7 8]]


In [40]:
print(arr1[1:,1:])

[[5 6]
 [8 9]]


In [41]:
print(arr1[:,0])

[1 4 7]


In [42]:
print(arr1[0,:])

[1 2 3]


Convert 1D to 2D Array

In [3]:
arr1=np.array([1,2,3,4,5,6])
print(arr1)
arr1=arr1.reshape(2,3)
print(arr1)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


Looping through array

In [5]:
arr1=np.array([[1,2,3], [4,5,6], [7,8,9]])
for i in arr1:
    for j in i:
        print(j)


1
2
3
4
5
6
7
8
9


Add 10 to Each Element

In [6]:
print(arr1+10)        #this is known as broadcasting we are adding 10 to each element 

[[11 12 13]
 [14 15 16]
 [17 18 19]]


Multiply Arrays

In [7]:
a=np.array([[1,2], [3,4]])                 #normal multiply it is multiply the element on same position
b=np.array([[1,2], [3,4]])
print(a*b)

[[ 1  4]
 [ 9 16]]


In [8]:
print(a@b)                   #matrix multiplu see concept in notebook this we have done in class 12

[[ 7 10]
 [15 22]]


Find mean, median, mode

In [ ]:
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

In [14]:
#find out mode
!pip install scipy


Defaulting to user installation because normal site-packages is not writeable


In [15]:
from scipy import stats
arr1=np.array([10,10,10,20,30,40])
print(stats.mode(arr1))

ModeResult(mode=np.int64(10), count=np.int64(3))


You have marks of students:

marks = [45, 78, 90, 66, 88, 72, 59]
Tasks:  
Convert to NumPy array  
Find average marks  
Find highest & lowest marks  
Find students scoring above average  
Add 5 grace marks to all students

In [9]:
marks=np.array([45, 78, 90, 66, 88, 72, 59])
print(marks)
print("Average is",np.mean(marks))
print("highest marks is",np.max(marks))
print("lowest marks is",np.min(marks))
print("add 5 grace marks is",marks+5)

[45 78 90 66 88 72 59]
Average is 71.14285714285714
highest marks is 90
lowest marks is 45
add 5 grace marks is [50 83 95 71 93 77 64]


In [17]:
#students scoring marks above average 
print(marks>np.mean(marks))    #this will give true and false but we want element so for that do as following
print(marks[marks>np.mean(marks)])

[False  True  True False  True  True False]
[78 90 88 72]


Temperature recorded for 7 days:

temps = [30, 32, 35, 31, 29, 40, 38]
Tasks:  
Find days with temperature > 35  
Count number of hot days   

In [29]:
temps=np.array( [30, 32, 35, 31, 29, 40, 38])
print("days greater than temp 35 are", temps[temps>35])
print("no, of hot days are",len(temps))


days greater than temp 35 are [40 38]
no, of hot days are 7


Employee salaries:  **(Homework questions)** 

salary = [25000, 40000, 35000, 50000, 45000]
Tasks:  
Increase all salaries by 10%  
Find employees earning > 40000   

In [42]:
salary=np.array([25000,40000,35000,50000,45000])
print("increased salaries by 10% are",salary*1.1 )
print("Employees earning more than 40000 are", salary[salary>40000])

increased salaries by 10% are [27500. 44000. 38500. 55000. 49500.]
Employees earning more than 40000 are [50000 45000]


A grayscale image (3x3 pixels):

img = [[100, 150, 200],
       [50, 75, 125],
       [0, 25, 255]]
Tasks:  
Convert to NumPy array  
Increase brightness by 20  
Clip values to max 255  

In [55]:
img=np.array([[100, 150, 200], [50, 75, 125], [0, 25, 255]])
print(img)
print("Increase brightness by 20 =",img+20)
print(np.clip(img,0,255))                       #syntax of clipping=np.clip(array name,lower value,value told by ques maximum)

[[100 150 200]
 [ 50  75 125]
 [  0  25 255]]
Increase brightness by 20 = [[120 170 220]
 [ 70  95 145]
 [ 20  45 275]]
[[100 150 200]
 [ 50  75 125]
 [  0  25 255]]


Sales for 5 days:

sales = [200, 300, 250, 400, 350]
Tasks:  
Find total sales  
Find day with highest sales  
Find days where sales < 300  

In [63]:
sales=np.array([200, 300, 250, 400, 350])   
print("total sales are", np.sum(sales))
print("sales less than  300 are", sales[sales<300])

total sales are 1500
sales less than  300 are [200 250]


Scores:

scores = [55, 65, 75, 85, 95]
Tasks:  
Get students with grades ≥ 75  
Replace scores < 60 with 60  

In [66]:
scores=np.array( [55, 65, 75, 85, 95] )
print("students with grades more than equals to 75 are",scores[scores<300])


students with grades more than equals to 75 are [55 65 75 85 95]


## homework questions of 31 march class python

In [74]:
quote = "In this World nothing can be said to be Certain, Except Death and Taxes."

i=0

while i<len(quote):
    if quote[i].isupper():
        print(quote[i])
    i+=1    #this means i=i+1

len(quote) #this is to show you the length of quote including blanks

I
W
C
E
D
T


72

**Exercise 3:** You have `people = ['Ana','Ben','Cara']` and `scores = [92, 85, 92]`. Use zip() to pair them and build a dict; if a name repeats, keep the higher score.